export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'

export const CURRENT_USER_POSTS_UPDATE = 'CURRENT_USER_POSTS_UPDATE'

export const MODAL_OPEN_QA = 'MODAL_OPEN_QA'
export const MODAL_OPEN_DESCRIPTION = 'MODAL_OPEN_DESCRIPTION'
export const MODAL_OPEN_OPTIONS = 'MODAL_OPEN_OPTIONS'
export const MODAL_OPEN_BUYNOW = 'MODAL_OPEN_BUYNOW'

export const CLEAR_MODAL = 'CLEAR_MODAL'
